name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - '.releaserc.base.cjs'

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - sylph-jsx
          # Add new packages here
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for releasable commits
        id: changes
        run: |
          cd packages/${{ matrix.package }}

          if npx semantic-release --dry-run 2>&1 | grep -q "Published release"; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Build ${{ matrix.package }}
        if: steps.changes.outputs.has_changes == 'true'
        run: npm run build -w ${{ matrix.package }}

      - name: Release ${{ matrix.package }}
        if: steps.changes.outputs.has_changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: |
          cd packages/${{ matrix.package }}
          npx semantic-release
