name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - '.releaserc.base.cjs'

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  actions: write

jobs:
  release:
    name: Release packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - sylph-jsx
          # Add new packages here
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Build ${{ matrix.package }}
        run: npm run build -w ${{ matrix.package }}

      - name: Release ${{ matrix.package }}
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          GIT_AUTHOR_NAME: "github-actions[bot]"
          GIT_AUTHOR_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
          GIT_COMMITTER_NAME: "github-actions[bot]"
          GIT_COMMITTER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
        run: |
          cd packages/${{ matrix.package }}

          # Run semantic-release; if no release occurred, the workspace stays clean
          npx semantic-release

          if git status --porcelain; then
            echo "released=true" >> $GITHUB_OUTPUT
          else
            echo "released=false" >> $GITHUB_OUTPUT
            echo "No release needed"
          fi

